// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_sdcable.Models;

namespace Mission06_sdcable.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_sdcable.Models.CategoriesModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Category = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 2,
                            Category = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 3,
                            Category = "Comedy"
                        },
                        new
                        {
                            CategoryId = 4,
                            Category = "Drama"
                        },
                        new
                        {
                            CategoryId = 5,
                            Category = "Family"
                        },
                        new
                        {
                            CategoryId = 6,
                            Category = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 7,
                            Category = "Miscellaneous"
                        },
                        new
                        {
                            CategoryId = 8,
                            Category = "Television"
                        },
                        new
                        {
                            CategoryId = 9,
                            Category = "VHS"
                        });
                });

            modelBuilder.Entity("Mission06_sdcable.Models.MovieModel", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "Chris Columbus",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Harry Potter and the Sorcerer's Stone",
                            Year = 2001
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 2,
                            Director = "George Lucas",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Star Wars: Episode IV -- A New Hope",
                            Year = 1977
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 5,
                            Director = "Chris McKay",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "The Lego Batman Movie",
                            Year = 2017
                        });
                });

            modelBuilder.Entity("Mission06_sdcable.Models.MovieModel", b =>
                {
                    b.HasOne("Mission06_sdcable.Models.CategoriesModel", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
